### PR TITLE
Add machine arg to launch files to launch remotely

### PR DESCRIPTION
**Pull request by wkentaro**
For https://github.com/ros-drivers/openni2_launch/issues/32

### CODE REVIEW

**Comment by 130s** [comment]
+1

**Comment by furushchev** [comment]
@130s 
This pull request affects all other projects that use launch files in this package and if machine `localhost` is not defined anywhere in launch files it fails launching.
(for example https://github.com/ros-drivers/openni_launch/blob/indigo-devel/launch/openni.launch has no `machine` tag with `name="localhost"`, so `roslaunch openni_launch openni.launch` fails)
+1 to revert this change and discuss the solution.

**Comment by furushchev** [comment]
also see https://travis-ci.org/ros-drivers/rgbd_launch/builds/158368319

**Comment by 130s** [comment]
Then why did [the test for this PR](https://travis-ci.org/ros-drivers/rgbd_launch/builds/138551233) pass?

**Comment by furushchev** [comment]
@130s because my PR that enables testing (https://github.com/ros-drivers/rgbd_launch/pull/29)  has not yet merged.

I rebased in https://github.com/ros-drivers/rgbd_launch/pull/29 after this pull request was merged, and travis fails because of the change from this PR.
Anyway you can easily check that openni.launch fails at your local machine.

**Comment by furushchev** [comment]
@130s Also please note that adding machine tag was also discussed and reverted at the past, (https://github.com/ros-drivers/rgbd_launch/issues/5)

**Comment by 130s** [comment]
Now I understand the situation better thanks to @furushchev. I now agree to revert this PR because:
- A test file proposed in #29 (test/camera_for_test.launch) reveals that the change in this PR breaks existing application of this package.
  - My comment https://github.com/ros-drivers/rgbd_launch/pull/27#issuecomment-245505160 was based on an assumption that there was test files already in this package, which is false.
- <s>Exact</s> Same change and rollback happened before as in https://github.com/ros-drivers/rgbd_launch/pull/27#issuecomment-245506331 and this PR doesn't seem to provide a solution to it.

**Comment by 130s** [comment]
Sorry for a hasty merge. Now this is reverted #30.

@wkentaro If you could reopen with update to address the revealed issue, that'd be great.

**Pull request merged**
