### PR TITLE
[jade-devel] Cherry-pick recent commits. Adjust Travis conf to Jade & Kinetic

### PR DESCRIPTION
**Pull request by 130s**
Includes #28 #29 #31

### CODE REVIEW

**Comment by 130s** [comment]
Travis fails at [the newly added hz test](https://travis-ci.org/ros-drivers/rgbd_launch/jobs/159066364#L3435), which didn't fail for `indigo-devel`.

```
[rgbd_launch:make] [ROSTEST]-----------------------------------------------------------------------
[rgbd_launch:make] 
[rgbd_launch:make] [rgbd_launch.rosunit-hztest_tf/test_hz][FAILURE]--------------------------------
[rgbd_launch:make] no messages before timeout
[rgbd_launch:make]   File "/usr/lib/python2.7/unittest/case.py", line 331, in run
[rgbd_launch:make]     testMethod()
[rgbd_launch:make]   File "/opt/ros/indigo/share/rostest/nodes/hztest/hztest", line 117, in test_hz
[rgbd_launch:make]     self._test_hz(hz, hzerror, topic, test_duration, wait_time)
[rgbd_launch:make]   File "/opt/ros/indigo/share/rostest/nodes/hztest/hztest", line 152, in _test_hz
[rgbd_launch:make]     self.assert_(self.message_received, "no messages before timeout")
[rgbd_launch:make]   File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
[rgbd_launch:make]     raise self.failureException(msg)
[rgbd_launch:make] --------------------------------------------------------------------------------
[rgbd_launch:make] 
[rgbd_launch:make] 
[rgbd_launch:make] SUMMARY
[rgbd_launch:makem]  * RESULT: FAIL
[rgbd_launch:make]  * TESTS: 1
[rgbd_launch:make]  * ERRORS: 0
[rgbd_launch:make]  * FAILURES: 1
```

Since the hz test looks at `/tf` topic, this error might be related to https://github.com/ros-drivers/rgbd_launch/pull/18 where `tf2` is introduced for `jade-devel` onward.

Running locally, `/tf` is not published, which wasn't the case on Indigo.

```
roslaunch rgbd_launch camera_for_test.launch

rostopic echo /tf
(nothing returned)
```

**Comment by 130s** [comment]
I don't have any time this week to look into the errors on Travis. If possible @furushchev would you take a look?

**Comment by furushchev** [comment]
@130s Since `tf2` no more publishes periodic topic like `/tf` in `tf` ecosystem, testing with `hztest` does not mean any more.
I doubt that migrating from `tf` to `tf2` is necessary for jade and later, so the safest way is reverting to use `tf` also on jade/kinetic.

**Comment by 130s** [comment]
@furushchev thanks. Do you think using tf2 causes runtime error? If so we need to think of reverting. Else, we might just remove hztest for now (need to come up with another runtime test).

CC @DaikiMaekawa as the original writer of #18

**Comment by furushchev** [comment]
@130s Or we can change test method to more `tf` way, like checking transform can be looked up instead of just checking `/tf` topic is published.

**Comment by 130s** [comment]
@furushchev That sounds nice and simpler.

**Comment by furushchev** [comment]
@130s Created pull requests for each distros.
Please note that we will have to be careful to incompatibility every time cherry picking from one distro to another.
Cc: @DaikiMaekawa

**Pull request merged**
