### PR TITLE
Add queue_size option

### PR DESCRIPTION
**Pull request by iory**
I add queue_size option for launch file.

### CODE REVIEW

**Comment by iory** [comment]
kindly ping @130s

**Comment by 130s** [comment]
I only joined the maintenance team only because I thought I'd be able to help making releases, and I'm not necessarily qualifying for code review.

That said, I took a brief look.
```
$ ack -i queue_size .

$ git log -1
commit 2123238c24a4b9a59106f8264893bca9dc278462 (HEAD -> indigo-devel, origin/indigo-devel, origin/HEAD)
Merge: 3d4aec0 b7b6834
Author: Isaac I.Y. Saito <130s@users.noreply.github.com>
Date:   Tue Sep 13 17:47:37 2016 -0700

    Merge pull request #34 from furushchev/test-kinect-frames-indigo

    [test/test_kinect_frames.py] add test node for kinect_frames.launch
```
`queue_size` cannot be found inside of this package. Meaning, users might not be able to utilize this addition unless the usage is documented somewhere. Looks like the best documentation for this package is not in the repo but http://wiki.ros.org/rgbd_launch. Can you add it there and notify here?

**Comment by iory** [comment]
Thank you for your comment!
I add the documents about ```queue_size``` to ```rgbd_launch```'s ros wiki page.
http://wiki.ros.org/rgbd_launch#Arguments
Please confirm when you have time.

**Comment by iory** [comment]
kindly ping @130s

**Review by 130s — APPROVED** [review]
Again I'm not well qualified to give a code review for this repo. That said this rested for a few years without any downvotes so I'm merging now.

@iory Mind opening a quick PR to cherry-pick your change to `noetic-devel` branch? There should be no regression with your change as the only actual addition on that branch is this CMake change https://github.com/ros-drivers/rgbd_launch/commit/f816a6ff07c3b06483a0bd1238510448187c3fe2

**Pull request merged**
