### PR TITLE
Add convert_metric nodes to depth_registered.launch.xml

### LINKED ISSUE #11: Missing convert_metric node in depth_registered.launch.xml
depth.launch.xml includes a node that converts the raw depth image to a distance-in-meters image that is displayable with image_view and useful for querying.  Please add this node to depth_registered.launch.xml:

```
  <!-- Rectified depth image -->
  <node pkg="nodelet" type="nodelet" name="$(arg depth_registered)_metric_rect"
        args="load depth_image_proc/convert_metric $(arg manager) $(arg bond)"
        respawn="$(arg respawn)">
    <remap from="image_raw" to="$(arg depth_registered)/image_rect_raw" />
    <remap from="image"     to="$(arg depth_registered)/image_rect" />
  </node>

  <!-- Unrectified depth image -->
  <node pkg="nodelet" type="nodelet" name="$(arg depth_registered)_metric"
        args="load depth_image_proc/convert_metric $(arg manager) $(arg bond)"
        respawn="$(arg respawn)">
    <remap from="image_raw" to="$(arg depth_registered)/image_raw" />
    <remap from="image"     to="$(arg depth_registered)/image" />
  </node>

```

### PR DESCRIPTION
**Pull request by kbogert**
Fixes #11

### CODE REVIEW

**Comment by jbohren** [comment]
+1

**Comment by piyushk** [comment]
Sorry for the delay. I've been away for the summer. 

I'll merge the PR next week when I can run some tests. Is it absolutely essential to have this PR merged into Hydro? I would prefer to make updates only to the Indigo release if possible.

**Comment by kbogert** [comment]
This bug is annoying since there's no immediately apparent explanation for why the image topic isn't published when the registered depth image is used, but merging into indigo is fine.

**Comment by piyushk** [comment]
Could you redirect the PR to Indigo? Additionally, if you have the ability to test in Indigo, please run a test before submitting the PR. I don't have Indigo setup here.

Thanks!

**Comment by kbogert** [comment]
After all the trouble I went through to try and get a turtlebot2 and kinect working with Indigo, I would appreciate it if you would consider merging this PR as it looks like we'll be sticking with hydro for the foreseeable future.

**Comment by jbohren** [comment]
@kbogert Out of curiosity, why are you staying on Hydro for now?

**Comment by kbogert** [comment]
We run a number of turtlebot 1 & 2's with laptops currently with hydro on 12.04.  After spending the better part of today with a test laptop first trying to get the indigo turtlebot packages to compile and then fighting with openni/sensorkinect (see #14) there's no way I'm doing an upgrade until things work out of the box like they do with hydro.

**Comment by piyushk** [comment]
@kbogert I understand your concern. We're not moving away from Hydro as well for the same reason :). I'm just a bit scared about breaking openni_launch for anyone, since Hydro has been stable for a while. Since this PR is only adding new nodes, I think it's reasonable to introduce it into Hydro with minor version revision.

I've made the following changes to your pull request and submitted a PR to kbogert/hydro-devel (https://github.com/kbogert/rgbd_launch/pull/1). It makes the following changes:
1) There is an error with your current PR, since depth_registered/image_rect_raw does not exist. There are separate s/w and h/w processing pipelines, and I've changed the PR to add convert metric nodes in each pipeline:
- depth_registered/hw_registered/image_rect_raw -> depth_registered/hw_registered/image_rect
- depth_registered/sw_registered/image_rect_raw -> depth_registered/sw_registered/image_rect

Unfortunately, we cannot map these to the same topic, or else the driver starts throwing out a bunch of warnings. Is this acceptable?

2) Fixed some minor indentation issues.

If the changes seem fine with you, please accept the PR and ping this thread again. We can then merge these changes into Indigo in a separate commit.

**Comment by kbogert** [comment]
Thank you!  One thing to note is that I'm only able to test the hw_registered nodes.  The software ones don't seem to work for me, as it seems when the registered processing is enabled the unregistered nodes (which the sw_registered uses) aren't ever published.

**Comment by piyushk** [comment]
Thanks for testing! That's correct and expected behavior. I tested the sw_registered topics with registered processing disabled, and it seems to be running as expected.

**Pull request merged**
