### PR TITLE
Modified to use tf2 instead of tf

### PR DESCRIPTION
**Pull request by DaikiMaekawa**
[Review on Reviewable](https://reviewable.io/reviews/ros-drivers/rgbd_launch/16)

### CODE REVIEW

**Comment by DaikiMaekawa** [comment]
@piyushk Can you review the PR?

**Comment by piyushk** [comment]
@DaikiMaekawa I'll try and take a look at it within the week.

**Comment by DaikiMaekawa** [comment]
thx!

**Comment by DaikiMaekawa** [comment]
@piyushk Did you already test that?

**Comment by piyushk** [comment]
@DaikiMaekawa Apologies for the delay. I've just started looking at this request.

**Comment by piyushk** [comment]
@DaikiMaekawa This PR causes significant behavior change - The tf publication switches from /tf to /tf_static. 

Since the Indigo release has been out for a while, I can only merge this into the upcoming Jade release. Is there a specific reason why this change is necessary?

**Comment by 130s** [comment]
> Since the Indigo release has been out for a while, I can only merge this into the upcoming Jade release.

You mean K-turtle @piyushk since Jade has also been there for awhile?

**Comment by piyushk** [comment]
@130s I meant that rgbd_launch has not been released into Jade, so its unlikely someone who might be affected by this change has migrated to it.

**Comment by 130s** [comment]
D'oh, you're right. I'm a real dunderhead here since [it's me who just released it into Jade](https://github.com/ros-drivers/rgbd_launch/issues/17#issuecomment-157231850). It will get synced soon so do we want to create `jade-devel` and make a new release?

**Comment by piyushk** [comment]
That sounds good.

**Comment by 130s** [comment]
Ok. 
Closing in favor of #18.

**Pull request closed without merging**
